[package]
name = "moonsprite-thumbnail-provider"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "moonsprite_thumbnail"
crate-type = ["cdylib", "rlib"]

[workspace]

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
windows = { version = "0.62", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
  "Win32_UI_Shell_PropertiesSystem",
] }
windows-core = "0.62"
zip = { version = "4", default-features = false, features = ["deflate"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
