import { translateSourceText, type AppLocale } from '@/core/localization'
import type { ShortcutGroupId, ShortcutId } from '@/core/shortcuts'
import { CYCLING_TOOL_SHORTCUT_IDS, quickToolShortcutId, type QuickToolShortcutId } from '@/core/tool-shortcut-ids'

type BaseShortcutId = Exclude<ShortcutId, QuickToolShortcutId>

const zhGroups: Record<ShortcutGroupId, string> = {
  file: '文件', edit: '编辑', selection: '选区', image: '图像', color: '颜色与调色板', layers: '图层', animation: '动画', view: '视图', interface: '界面与栏目', tools: '工具', tiles: '瓦片', brushes: '图案笔刷', modifiers: '工具修饰', help: '帮助'
}

const enGroups: Record<ShortcutGroupId, string> = {
  file: 'File', edit: 'Edit', selection: 'Selection', image: 'Image', color: 'Color & Palette', layers: 'Layers', animation: 'Animation', view: 'View', interface: 'Interface & Panels', tools: 'Tools', tiles: 'Tiles', brushes: 'Pattern Brushes', modifiers: 'Tool Modifiers', help: 'Help'
}

const zhBaseLabels: Record<BaseShortcutId, string> = {
  'tool.slice': '切片工具',
  'tool.text': '文本工具',
  toggleClippingMask: '剪贴蒙版',
  toggleAnimationPlayback: '播放或暂停动画', previousAnimationFrame: '上一帧', nextAnimationFrame: '下一帧', addAnimationFrame: '新增帧', addLinkedAnimationFrame: '新建链接帧', addBlankAnimationFrame: '新建空帧', deleteAnimationFrame: '删除帧', copyAnimationCel: '复制单元格',
  openHome: '打开主页', newDocument: '新建工程', openDocument: '打开工程', closeDocument: '关闭工程', openProjectFolder: '在文件夹中打开', exportDocument: '导出', exportAllFrames: '导出所有帧', exportSpriteSheet: '导出精灵表', openTimelapse: '缩时动画', openProjectInfo: '项目信息',
  'tool.airbrush': '喷枪', 'tool.pencil': '画笔', 'tool.eraser': '橡皮擦', 'tool.selection': '矩形选区', 'tool.selection.ellipse': '椭圆选区', 'tool.move': '移动工具', 'tool.shape': '形状工具', 'tool.line': '直线工具', 'tool.curve': '曲线工具', 'tool.fill': '油漆桶', 'tool.fill.gradient': '渐变工具', 'tool.eyedropper': '吸管', 'tool.hand': '抓手', 'tool.zoom': '缩放工具', 'tool.rotate': '旋转视图',
  'tool.shape.rectangleOutline': '矩形轮廓', 'tool.shape.rectangle': '填充矩形', 'tool.shape.ellipseOutline': '椭圆轮廓', 'tool.shape.ellipse': '填充椭圆',
  lasso: '套索选区', polygonLasso: '多边形套索', magic: '魔棒选区', canvasResize: '调整画布大小', imageResize: '调整图像大小', transform: '变换', outline: '描边', adjustmentColorBalance: '色彩平衡', adjustmentBrightnessContrast: '亮度/对比度', adjustmentHueSaturation: '色相/饱和度', adjustmentCurves: '曲线', openShortcutSettings: '快捷键设置', openPreferences: '首选项', flipVertical: '垂直翻转', flipHorizontal: '水平翻转', selectAll: '全选', invertSelection: '反选选区', deselect: '取消选择', createBrushFromSelection: '从选区创建笔刷',
  copy: '复制', cut: '剪切', paste: '粘贴', pasteAsNewLayer: '粘贴为新图层', pasteAsNewDocument: '粘贴为新项目', save: '保存', saveAs: '另存为', undo: '撤销', redo: '重做', relativeLuminance: '查看相对明暗', advancedMode: '高级模式', fillForeground: '填充前景色', addForegroundToPalette: '按住并点击添加颜色', swapForegroundBackground: '交换前景色与背景色', replaceColor: '替换颜色', convertColorMode: '转换颜色模式', newLayer: '新建图层', createLayerGroup: '新建图层组', toggleSelectedLayerVisibility: '显示或隐藏所选图层', toggleSelectedLayerLock: '锁定或解锁所选图层', toggleSelectedGroupCollapsed: '展开或收起所选图层组', duplicateLayer: '复制图层', mergeLayerDown: '向下合并', mergeSelectedLayers: '合并所选图层', mergeLayerGroup: '合并图层组', mergeVisibleLayers: '合并可见图层', ungroupLayers: '解组', deleteLayer: '删除图层或选区', toggleSelectionOutline: '显示或隐藏蚂蚁线', mirrorView: '水平镜像视图', mirrorViewVertical: '垂直镜像视图', toggleGrid: '显示像素网格', toggleCustomGrid: '显示自定义网格', toggleIsoView: '切换默认/ISO绘制视角', openGridSettings: '网格设置', openIsoViewSettings: 'ISO绘制视角设置', rotateViewClockwise90: '顺时针旋转视图 90°', rotateViewCounterClockwise90: '逆时针旋转视图 90°', resetView: '复位视图', toggleColorPanel: '显示或隐藏颜色栏目', togglePalettePanel: '显示或隐藏调色板栏目', toggleLayersPanel: '显示或隐藏图层栏目', togglePreviewPanel: '显示或隐藏预览栏目', toggleTilesetPanel: '显示或隐藏瓦片集栏目', toggleBrushLibraryPanel: '显示或隐藏图案笔刷栏目', popupColorPanel: '弹窗式颜色栏目', popupPalettePanel: '弹窗式调色板栏目', popupLayersPanel: '弹窗式图层栏目', popupPreviewPanel: '弹窗式预览栏目', popupTilesetPanel: '弹窗式瓦片集栏目', popupBrushLibraryPanel: '弹窗式图案笔刷栏目', toggleTimeline: '显示或隐藏时间轴', toolRailLeft: '工具栏放到左侧', toolRailRight: '工具栏放到右侧', toolRailTop: '工具栏放到顶部', toolRailBottom: '工具栏放到底部', saveWorkspaceLayout: '保存为新工作区', openWorkspaceManager: '管理工作区', openComponentLibrary: '组件库', openLatestRelease: '更新日志', openAbout: '关于 MoonSprite',
  brushSizeDecrease: '减小笔刷尺寸', brushSizeIncrease: '增大笔刷尺寸', copySelectionContent: '复制选区内容', copyLayerOnDrag: '拖动复制图层', constrainAxis: '水平或垂直约束', addToSelection: '加选', proportionalSelectionTransform: '选区固定比例缩放', integerSelectionScale: '选区整数倍缩放', snapSelectionRotation: '选区八方向旋转', snapViewRotation: '视图八方向旋转', resetViewRotation: '旋转视图临时复位', brushSizeAdjust: '拖动调整笔刷尺寸', brushSizeWheelAdjust: '滚轮调整笔刷尺寸', lineConnectionMode: '直线连接模式', constrainLineDirections: '约束直线方向',
  openScriptFolder: '打开脚本文件夹',
  'tool.shape.freeform': '自由形状', 'tool.shape.polygon': '多边形形状',
  deleteSelection: '删除选区内容', selectionModeReplace: '选区模式：替换', selectionModeAdd: '选区模式：添加', selectionModeSubtract: '选区模式：减去', selectionModeIntersect: '选区模式：交集', selectAllSlices: '选择全部切片', openAutoSlice: '自动切片', openSliceProperties: '切片属性',
  convertColorModeRgba: '转换为 RGBA', convertColorModeIndexed: '转换为索引颜色', convertColorModeGrayscale: '转换为灰度', cropCanvas: '裁切到选区', trimCanvas: '修剪到可见内容',
  togglePaletteEditLock: '锁定或解锁调色板编辑', extractPaletteColors: '从当前图像提取颜色', togglePaletteColorSync: '同步或取消同步调色板颜色', reversePaletteColors: '反转调色板颜色', createPaletteGradient: '创建调色板渐变', createPaletteHueGradient: '创建调色板色相渐变', sortPaletteHue: '调色板按色相排序', sortPaletteSaturation: '调色板按饱和度排序', sortPaletteBrightness: '调色板按亮度排序', sortPaletteLuminance: '调色板按明度排序', sortPaletteRed: '调色板按红色通道排序', sortPaletteGreen: '调色板按绿色通道排序', sortPaletteBlue: '调色板按蓝色通道排序', sortPaletteAlpha: '调色板按透明度排序', paletteSortAscending: '调色板升序排序', paletteSortDescending: '调色板降序排序', paletteSwatchTiny: '调色板色块：极小', paletteSwatchSmall: '调色板色块：小', paletteSwatchMedium: '调色板色块：中', paletteSwatchLarge: '调色板色块：大', paletteSwatchHuge: '调色板色块：巨大', savePalette: '保存调色板', openPaletteFolder: '打开调色板文件夹', refreshPalettes: '刷新本地调色板',
  newTilemapLayer: '新建瓦片图层', newFreeTileLayer: '新建自由瓦片图层', newBackgroundLayer: '新建背景图层', createLinkedLayer: '创建关联图层', convertLayerToBackground: '转换为背景图层', convertLayerToTilemap: '转换为瓦片图层', convertLayerToRaster: '转换为普通图层', openLayerProperties: '图层属性', openLayerStyles: '图层样式', toggleLayerStyles: '启用或停用图层样式', copyLayerStyles: '复制图层样式', pasteLayerStyles: '粘贴图层样式', clearLayerStyles: '清除图层样式', toggleLayerMask: '创建图层蒙版', toggleGroupMask: '创建或删除图层组蒙版', openLayerSettings: '图层栏目设置',
  toggleSliceOutlines: '显示或隐藏切片边框', tileRepeatOff: '关闭平铺模式', tileRepeatBoth: '包围平铺', tileRepeatX: 'X 轴平铺', tileRepeatY: 'Y 轴平铺',
  resetWorkspaceLayout: '复位当前工作区',
  brushShapeRound: '基础笔刷：圆形', brushShapeSquare: '基础笔刷：方形', brushShapeLine: '基础笔刷：线形', togglePerfectPixels: '完美像素', toggleContiguous: '连续', toggleSmartClosure: '智能闭合', toggleRoundedCorners: '圆角', toggleFixedRatio: '固定比例', toggleMoveAutoSelect: '移动工具自动选择图层', toggleSymmetryHorizontal: '水平对称轴', toggleSymmetryVertical: '垂直对称轴', toggleSymmetryDiagonalUp: '上升斜向对称轴', toggleSymmetryDiagonalDown: '下降斜向对称轴', toggleSymmetryRotational: '旋转对称轴', resetSymmetryCenter: '复位对称轴中心',
  tilemapModeEdit: '瓦片模式：原位编辑', tilemapModeCreate: '瓦片模式：变体创建', tilemapModeHybrid: '瓦片模式：混合编辑', tilemapModePaint: '瓦片模式：绘制瓦片', freeTileModeEdit: '自由瓦片模式：编辑源瓦片', freeTileModePaint: '自由瓦片模式：放置实例', addFreeTileSource: '新增源瓦片', deleteTilesetSelection: '删除所选瓦片', openFreeTileSourceProperties: '源瓦片属性', showOnlyFreeTileInstance: '仅显示所选瓦片实例', openFreeTileInstanceProperties: '瓦片实例属性', rotateFreeTileInstance90: '瓦片实例旋转 90°', mirrorFreeTileInstanceHorizontal: '瓦片实例水平镜像', mirrorFreeTileInstanceVertical: '瓦片实例垂直镜像', deleteFreeTileInstances: '删除所选瓦片实例',
  importBrushImage: '导入图案笔刷图片', createBrushFolder: '新建笔刷文件夹', openBrushFolder: '打开笔刷文件夹', refreshBrushLibrary: '刷新图案笔刷', brushLibraryParentFolder: '返回笔刷上一级文件夹', brushSwatchSmall: '笔刷预览：小', brushSwatchMedium: '笔刷预览：中', brushSwatchLarge: '笔刷预览：大', deleteBrushSelection: '删除所选图案笔刷',
  copyAnimationFrames: '复制所选帧', pasteAnimationFrames: '粘贴帧', pasteAnimationCels: '粘贴单元格', copyAnimationMasks: '复制蒙版单元格', pasteAnimationMasks: '粘贴蒙版单元格', connectAnimationCels: '关联所选单元格', disconnectAnimationCels: '断开所选单元格关联', connectAnimationMasks: '关联所选蒙版单元格', disconnectAnimationMasks: '断开所选蒙版单元格关联', toggleAnimationMask: '创建或删除当前单元格蒙版', createAnimationLoopSection: '新建动画循环节', openAnimationFrameProperties: '帧属性', playAnimationLoopSection: '播放当前循环节', openAnimationLoopSectionProperties: '循环节属性', deleteAnimationLoopSection: '删除当前循环节', openAnimationCelProperties: '单元格属性', animationPlaybackOnce: '动画播放模式：播放一次', animationPlaybackAll: '动画播放模式：循环全部帧', animationPlaybackTag: '动画播放模式：循环当前循环节', toggleAnimationReturnToStart: '停止时返回开始帧', animationPlaybackSpeed025: '动画播放速度：0.25x', animationPlaybackSpeed050: '动画播放速度：0.5x', animationPlaybackSpeed100: '动画播放速度：1x', animationPlaybackSpeed150: '动画播放速度：1.5x', animationPlaybackSpeed200: '动画播放速度：2x', animationPlaybackSpeed300: '动画播放速度：3x'
}

const enBaseLabels: Record<BaseShortcutId, string> = {
  'tool.slice': 'Slice Tool',
  'tool.text': 'Text Tool',
  toggleClippingMask: 'Clipping Mask',
  toggleAnimationPlayback: 'Play or Pause Animation', previousAnimationFrame: 'Previous Frame', nextAnimationFrame: 'Next Frame', addAnimationFrame: 'Add Frame', addLinkedAnimationFrame: 'New Linked Frame', addBlankAnimationFrame: 'New Blank Frame', deleteAnimationFrame: 'Delete Frame', copyAnimationCel: 'Copy Cel',
  openHome: 'Open Home', newDocument: 'New Project', openDocument: 'Open Project', closeDocument: 'Close Project', openProjectFolder: 'Show in Folder', exportDocument: 'Export', exportAllFrames: 'Export All Frames', exportSpriteSheet: 'Export Sprite Sheet', openTimelapse: 'Timelapse', openProjectInfo: 'Project Information',
  'tool.airbrush': 'Airbrush', 'tool.pencil': 'Pencil', 'tool.eraser': 'Eraser', 'tool.selection': 'Rectangular Selection', 'tool.selection.ellipse': 'Elliptical Selection', 'tool.move': 'Move Tool', 'tool.shape': 'Shape Tool', 'tool.line': 'Line Tool', 'tool.curve': 'Curve Tool', 'tool.fill': 'Paint Bucket', 'tool.fill.gradient': 'Gradient Tool', 'tool.eyedropper': 'Eyedropper', 'tool.hand': 'Hand Tool', 'tool.zoom': 'Zoom Tool', 'tool.rotate': 'Rotate View',
  'tool.shape.rectangleOutline': 'Rectangle Outline', 'tool.shape.rectangle': 'Filled Rectangle', 'tool.shape.ellipseOutline': 'Ellipse Outline', 'tool.shape.ellipse': 'Filled Ellipse',
  lasso: 'Lasso Selection', polygonLasso: 'Polygonal Lasso', magic: 'Magic Wand Selection', canvasResize: 'Canvas Size', imageResize: 'Image Size', transform: 'Transform', outline: 'Outline', adjustmentColorBalance: 'Color Balance', adjustmentBrightnessContrast: 'Brightness/Contrast', adjustmentHueSaturation: 'Hue/Saturation', adjustmentCurves: 'Curves', openShortcutSettings: 'Keyboard Shortcuts', openPreferences: 'Preferences', flipVertical: 'Flip Vertically', flipHorizontal: 'Flip Horizontally', selectAll: 'Select All', invertSelection: 'Invert Selection', deselect: 'Deselect', createBrushFromSelection: 'Create Brush from Selection',
  copy: 'Copy', cut: 'Cut', paste: 'Paste', pasteAsNewLayer: 'Paste as New Layer', pasteAsNewDocument: 'Paste as New Project', save: 'Save', saveAs: 'Save As', undo: 'Undo', redo: 'Redo', relativeLuminance: 'Relative Luminance', advancedMode: 'Advanced Mode', fillForeground: 'Fill with Foreground Color', addForegroundToPalette: 'Hold and Click to Add Color', swapForegroundBackground: 'Swap Foreground and Background', replaceColor: 'Replace Color', convertColorMode: 'Convert Color Mode', newLayer: 'New Layer', createLayerGroup: 'New Layer Group', toggleSelectedLayerVisibility: 'Show or Hide Selected Layers', toggleSelectedLayerLock: 'Lock or Unlock Selected Layers', toggleSelectedGroupCollapsed: 'Expand or Collapse Selected Groups', duplicateLayer: 'Duplicate Layer', mergeLayerDown: 'Merge Down', mergeSelectedLayers: 'Merge Selected Layers', mergeLayerGroup: 'Merge Layer Group', mergeVisibleLayers: 'Merge Visible Layers', ungroupLayers: 'Ungroup', deleteLayer: 'Delete Layer or Selection', toggleSelectionOutline: 'Show or Hide Marching Ants', mirrorView: 'Mirror View Horizontally', mirrorViewVertical: 'Mirror View Vertically', toggleGrid: 'Show Pixel Grid', toggleCustomGrid: 'Show Custom Grid', toggleIsoView: 'Toggle Default/ISO Drawing Perspective', openGridSettings: 'Grid Settings', openIsoViewSettings: 'ISO Drawing Perspective Settings', rotateViewClockwise90: 'Rotate View 90° Clockwise', rotateViewCounterClockwise90: 'Rotate View 90° Counterclockwise', resetView: 'Reset View', toggleColorPanel: 'Show or Hide Color Panel', togglePalettePanel: 'Show or Hide Palette Panel', toggleLayersPanel: 'Show or Hide Layers Panel', togglePreviewPanel: 'Show or Hide Preview Panel', toggleTilesetPanel: 'Show or Hide Tileset Panel', toggleBrushLibraryPanel: 'Show or Hide Pattern Brushes Panel', popupColorPanel: 'Popup Color Panel', popupPalettePanel: 'Popup Palette Panel', popupLayersPanel: 'Popup Layers Panel', popupPreviewPanel: 'Popup Preview Panel', popupTilesetPanel: 'Popup Tileset Panel', popupBrushLibraryPanel: 'Popup Pattern Brushes Panel', toggleTimeline: 'Show or Hide Timeline', toolRailLeft: 'Move Toolbar to Left', toolRailRight: 'Move Toolbar to Right', toolRailTop: 'Move Toolbar to Top', toolRailBottom: 'Move Toolbar to Bottom', saveWorkspaceLayout: 'Save as New Workspace', openWorkspaceManager: 'Manage Workspaces', openComponentLibrary: 'Component Library', openLatestRelease: 'Release Notes', openAbout: 'About MoonSprite',
  brushSizeDecrease: 'Decrease Brush Size', brushSizeIncrease: 'Increase Brush Size', copySelectionContent: 'Copy Selection Content', copyLayerOnDrag: 'Duplicate Layer While Dragging', constrainAxis: 'Constrain Horizontally or Vertically', addToSelection: 'Add to Selection', proportionalSelectionTransform: 'Proportional Selection Scale', integerSelectionScale: 'Integer Selection Scale', snapSelectionRotation: 'Snap Selection Rotation to 8 Directions', snapViewRotation: 'Snap View Rotation to 8 Directions', resetViewRotation: 'Temporarily Reset View Rotation', brushSizeAdjust: 'Drag to Adjust Brush Size', brushSizeWheelAdjust: 'Wheel to Adjust Brush Size', lineConnectionMode: 'Line Connection Mode', constrainLineDirections: 'Constrain Line Directions',
  openScriptFolder: 'Open Scripts Folder',
  'tool.shape.freeform': 'Freeform Shape', 'tool.shape.polygon': 'Polygon Shape',
  deleteSelection: 'Delete Selection Contents', selectionModeReplace: 'Selection Mode: Replace', selectionModeAdd: 'Selection Mode: Add', selectionModeSubtract: 'Selection Mode: Subtract', selectionModeIntersect: 'Selection Mode: Intersect', selectAllSlices: 'Select All Slices', openAutoSlice: 'Auto Slice', openSliceProperties: 'Slice Properties',
  convertColorModeRgba: 'Convert to RGBA', convertColorModeIndexed: 'Convert to Indexed Color', convertColorModeGrayscale: 'Convert to Grayscale', cropCanvas: 'Crop to Selection', trimCanvas: 'Trim to Visible Content',
  togglePaletteEditLock: 'Lock or Unlock Palette Editing', extractPaletteColors: 'Extract Colors from Current Image', togglePaletteColorSync: 'Toggle Palette Color Synchronization', reversePaletteColors: 'Reverse Palette Colors', createPaletteGradient: 'Create Palette Gradient', createPaletteHueGradient: 'Create Palette Hue Gradient', sortPaletteHue: 'Sort Palette by Hue', sortPaletteSaturation: 'Sort Palette by Saturation', sortPaletteBrightness: 'Sort Palette by Brightness', sortPaletteLuminance: 'Sort Palette by Luminance', sortPaletteRed: 'Sort Palette by Red Channel', sortPaletteGreen: 'Sort Palette by Green Channel', sortPaletteBlue: 'Sort Palette by Blue Channel', sortPaletteAlpha: 'Sort Palette by Alpha', paletteSortAscending: 'Palette Sort Ascending', paletteSortDescending: 'Palette Sort Descending', paletteSwatchTiny: 'Palette Swatches: Tiny', paletteSwatchSmall: 'Palette Swatches: Small', paletteSwatchMedium: 'Palette Swatches: Medium', paletteSwatchLarge: 'Palette Swatches: Large', paletteSwatchHuge: 'Palette Swatches: Huge', savePalette: 'Save Palette', openPaletteFolder: 'Open Palettes Folder', refreshPalettes: 'Refresh Local Palettes',
  newTilemapLayer: 'New Tilemap Layer', newFreeTileLayer: 'New Free Tile Layer', newBackgroundLayer: 'New Background Layer', createLinkedLayer: 'Create Linked Layer', convertLayerToBackground: 'Convert to Background Layer', convertLayerToTilemap: 'Convert to Tilemap Layer', convertLayerToRaster: 'Convert to Normal Layer', openLayerProperties: 'Layer Properties', openLayerStyles: 'Layer Styles', toggleLayerStyles: 'Enable or Disable Layer Styles', copyLayerStyles: 'Copy Layer Styles', pasteLayerStyles: 'Paste Layer Styles', clearLayerStyles: 'Clear Layer Styles', toggleLayerMask: 'Create Layer Mask', toggleGroupMask: 'Create or Delete Group Mask', openLayerSettings: 'Layers Panel Settings',
  toggleSliceOutlines: 'Show or Hide Slice Outlines', tileRepeatOff: 'Disable Tile Repeat', tileRepeatBoth: 'Surround Tile Repeat', tileRepeatX: 'X Axis Tile Repeat', tileRepeatY: 'Y Axis Tile Repeat',
  resetWorkspaceLayout: 'Reset Current Workspace',
  brushShapeRound: 'Basic Brush: Round', brushShapeSquare: 'Basic Brush: Square', brushShapeLine: 'Basic Brush: Line', togglePerfectPixels: 'Perfect Pixels', toggleContiguous: 'Contiguous', toggleSmartClosure: 'Smart Closure', toggleRoundedCorners: 'Rounded Corners', toggleFixedRatio: 'Fixed Ratio', toggleMoveAutoSelect: 'Move Tool Auto Select Layer', toggleSymmetryHorizontal: 'Horizontal Symmetry Axis', toggleSymmetryVertical: 'Vertical Symmetry Axis', toggleSymmetryDiagonalUp: 'Rising Diagonal Symmetry Axis', toggleSymmetryDiagonalDown: 'Falling Diagonal Symmetry Axis', toggleSymmetryRotational: 'Rotational Symmetry Axis', resetSymmetryCenter: 'Reset Symmetry Center',
  tilemapModeEdit: 'Tile Mode: Edit in Place', tilemapModeCreate: 'Tile Mode: Create Variant', tilemapModeHybrid: 'Tile Mode: Hybrid Edit', tilemapModePaint: 'Tile Mode: Paint Tiles', freeTileModeEdit: 'Free Tile Mode: Edit Source', freeTileModePaint: 'Free Tile Mode: Place Instance', addFreeTileSource: 'Add Source Tile', deleteTilesetSelection: 'Delete Selected Tiles', openFreeTileSourceProperties: 'Source Tile Properties', showOnlyFreeTileInstance: 'Show Only Selected Tile Instance', openFreeTileInstanceProperties: 'Tile Instance Properties', rotateFreeTileInstance90: 'Rotate Tile Instance 90°', mirrorFreeTileInstanceHorizontal: 'Mirror Tile Instance Horizontally', mirrorFreeTileInstanceVertical: 'Mirror Tile Instance Vertically', deleteFreeTileInstances: 'Delete Selected Tile Instances',
  importBrushImage: 'Import Pattern Brush Image', createBrushFolder: 'Create Brush Folder', openBrushFolder: 'Open Brushes Folder', refreshBrushLibrary: 'Refresh Pattern Brushes', brushLibraryParentFolder: 'Go to Parent Brush Folder', brushSwatchSmall: 'Brush Preview: Small', brushSwatchMedium: 'Brush Preview: Medium', brushSwatchLarge: 'Brush Preview: Large', deleteBrushSelection: 'Delete Selected Pattern Brushes',
  copyAnimationFrames: 'Copy Selected Frames', pasteAnimationFrames: 'Paste Frames', pasteAnimationCels: 'Paste Cels', copyAnimationMasks: 'Copy Mask Cels', pasteAnimationMasks: 'Paste Mask Cels', connectAnimationCels: 'Link Selected Cels', disconnectAnimationCels: 'Unlink Selected Cels', connectAnimationMasks: 'Link Selected Mask Cels', disconnectAnimationMasks: 'Unlink Selected Mask Cels', toggleAnimationMask: 'Create or Delete Current Cel Mask', createAnimationLoopSection: 'Create Animation Loop Section', openAnimationFrameProperties: 'Frame Properties', playAnimationLoopSection: 'Play Current Loop Section', openAnimationLoopSectionProperties: 'Loop Section Properties', deleteAnimationLoopSection: 'Delete Current Loop Section', openAnimationCelProperties: 'Cel Properties', animationPlaybackOnce: 'Animation Playback: Play Once', animationPlaybackAll: 'Animation Playback: Loop All Frames', animationPlaybackTag: 'Animation Playback: Loop Current Section', toggleAnimationReturnToStart: 'Return to Start Frame on Stop', animationPlaybackSpeed025: 'Animation Playback Speed: 0.25x', animationPlaybackSpeed050: 'Animation Playback Speed: 0.5x', animationPlaybackSpeed100: 'Animation Playback Speed: 1x', animationPlaybackSpeed150: 'Animation Playback Speed: 1.5x', animationPlaybackSpeed200: 'Animation Playback Speed: 2x', animationPlaybackSpeed300: 'Animation Playback Speed: 3x'
}

const quickToolLabels = (
  labels: Record<BaseShortcutId, string>,
  suffix: string
): Record<QuickToolShortcutId, string> => Object.fromEntries(CYCLING_TOOL_SHORTCUT_IDS.map((id) => [
  quickToolShortcutId(id),
  `${labels[id]}${suffix}`
])) as Record<QuickToolShortcutId, string>

const zhLabels = { ...zhBaseLabels, ...quickToolLabels(zhBaseLabels, '（快速选择）') } as Record<ShortcutId, string>
const enLabels = { ...enBaseLabels, ...quickToolLabels(enBaseLabels, ' (Quick Select)') } as Record<ShortcutId, string>

// Keep an independent label table per locale. The command ids are shared, but
// the visible category names and quick-select suffixes must not point directly
// at the English table (which previously made every new locale display English).
const jaGroups: Record<ShortcutGroupId, string> = { file: 'ファイル', edit: '編集', selection: '選択', image: '画像', color: 'カラーとパレット', layers: 'レイヤー', animation: 'アニメーション', view: '表示', interface: 'インターフェースとパネル', tools: 'ツール', tiles: 'タイル', brushes: 'パターンブラシ', modifiers: 'ツール修飾', help: 'ヘルプ' }
const koGroups: Record<ShortcutGroupId, string> = { file: '파일', edit: '편집', selection: '선택', image: '이미지', color: '색상 및 팔레트', layers: '레이어', animation: '애니메이션', view: '보기', interface: '인터페이스 및 패널', tools: '도구', tiles: '타일', brushes: '패턴 브러시', modifiers: '도구 보정', help: '도움말' }
const esGroups: Record<ShortcutGroupId, string> = { file: 'Archivo', edit: 'Edición', selection: 'Selección', image: 'Imagen', color: 'Color y paleta', layers: 'Capas', animation: 'Animación', view: 'Vista', interface: 'Interfaz y paneles', tools: 'Herramientas', tiles: 'Mosaicos', brushes: 'Pinceles de patrón', modifiers: 'Modificadores', help: 'Ayuda' }
const frGroups: Record<ShortcutGroupId, string> = { file: 'Fichier', edit: 'Édition', selection: 'Sélection', image: 'Image', color: 'Couleur et palette', layers: 'Calques', animation: 'Animation', view: 'Affichage', interface: 'Interface et panneaux', tools: 'Outils', tiles: 'Tuiles', brushes: 'Pinceaux de motif', modifiers: 'Modificateurs', help: 'Aide' }
const deGroups: Record<ShortcutGroupId, string> = { file: 'Datei', edit: 'Bearbeiten', selection: 'Auswahl', image: 'Bild', color: 'Farbe und Palette', layers: 'Ebenen', animation: 'Animation', view: 'Ansicht', interface: 'Oberfläche und Bedienfelder', tools: 'Werkzeuge', tiles: 'Kacheln', brushes: 'Musterpinsel', modifiers: 'Werkzeugmodifikatoren', help: 'Hilfe' }
const ptGroups: Record<ShortcutGroupId, string> = { file: 'Arquivo', edit: 'Editar', selection: 'Seleção', image: 'Imagem', color: 'Cor e paleta', layers: 'Camadas', animation: 'Animação', view: 'Exibição', interface: 'Interface e painéis', tools: 'Ferramentas', tiles: 'Azulejos', brushes: 'Pincéis de padrão', modifiers: 'Modificadores', help: 'Ajuda' }
const ruGroups: Record<ShortcutGroupId, string> = { file: 'Файл', edit: 'Правка', selection: 'Выделение', image: 'Изображение', color: 'Цвет и палитра', layers: 'Слои', animation: 'Анимация', view: 'Вид', interface: 'Интерфейс и панели', tools: 'Инструменты', tiles: 'Тайлы', brushes: 'Текстурные кисти', modifiers: 'Модификаторы', help: 'Справка' }
const localizedShortcutLabels = (sourceLabels: Record<BaseShortcutId, string>, locale: AppLocale, suffix: string): Record<ShortcutId, string> => {
  const generic = {
    'ja-JP': 'コマンド', 'ko-KR': '명령', 'es-ES': 'Comando', 'fr-FR': 'Commande', 'de-DE': 'Befehl', 'pt-BR': 'Comando', 'ru-RU': 'Команда', 'zh-CN': '命令', 'en-US': 'Command'
  }[locale]
  const labels = Object.fromEntries(Object.entries(sourceLabels).map(([id, sourceText]) => [id, translateSourceText(locale, sourceText) || `${generic} ${sourceText}`])) as Record<BaseShortcutId, string>
  return { ...labels, ...quickToolLabels(labels, suffix) }
}
const jaLabels = localizedShortcutLabels(zhBaseLabels, 'ja-JP', '（クイック選択）')
const koLabels = localizedShortcutLabels(zhBaseLabels, 'ko-KR', ' (빠른 선택)')
const esLabels = localizedShortcutLabels(zhBaseLabels, 'es-ES', ' (selección rápida)')
const frLabels = localizedShortcutLabels(zhBaseLabels, 'fr-FR', ' (sélection rapide)')
const deLabels = localizedShortcutLabels(zhBaseLabels, 'de-DE', ' (Schnellauswahl)')
const ptLabels = localizedShortcutLabels(zhBaseLabels, 'pt-BR', ' (seleção rápida)')
const ruLabels = localizedShortcutLabels(zhBaseLabels, 'ru-RU', ' (быстрый выбор)')

export const shortcutGroupLabelsByLocale: Record<AppLocale, Record<ShortcutGroupId, string>> = {
  'zh-CN': zhGroups,
  'en-US': enGroups,
  'ja-JP': jaGroups,
  'ko-KR': koGroups,
  'es-ES': esGroups,
  'fr-FR': frGroups,
  'de-DE': deGroups,
  'pt-BR': ptGroups,
  'ru-RU': ruGroups
}

export const shortcutLabelsByLocale: Record<AppLocale, Record<ShortcutId, string>> = {
  'zh-CN': zhLabels,
  'en-US': enLabels,
  'ja-JP': jaLabels,
  'ko-KR': koLabels,
  'es-ES': esLabels,
  'fr-FR': frLabels,
  'de-DE': deLabels,
  'pt-BR': ptLabels,
  'ru-RU': ruLabels
}
