import type { AppLocale } from '@/core/localization'
import type { ShortcutGroupId, ShortcutId } from '@/core/shortcuts'

const zhGroups: Record<ShortcutGroupId, string> = {
  file: '文件', edit: '编辑', selection: '选区', image: '图像', color: '颜色', layers: '图层', animation: '动画', view: '视图', interface: '界面与栏目', tools: '工具', modifiers: '工具修饰', help: '帮助'
}

const enGroups: Record<ShortcutGroupId, string> = {
  file: 'File', edit: 'Edit', selection: 'Selection', image: 'Image', color: 'Color', layers: 'Layers', animation: 'Animation', view: 'View', interface: 'Interface & Panels', tools: 'Tools', modifiers: 'Tool Modifiers', help: 'Help'
}

const zhLabels: Record<ShortcutId, string> = {
  'tool.slice': '切片工具',
  'tool.text': '文本工具',
  toggleClippingMask: '剪贴蒙版',
  toggleAnimationPlayback: '播放或暂停动画', previousAnimationFrame: '上一帧', nextAnimationFrame: '下一帧', addAnimationFrame: '新增帧', addLinkedAnimationFrame: '新建链接帧', addBlankAnimationFrame: '新建空帧', deleteAnimationFrame: '删除帧', copyAnimationCel: '复制单元格',
  openHome: '打开主页', newDocument: '新建工程', openDocument: '打开工程', closeDocument: '关闭工程', openProjectFolder: '在文件夹中打开', exportDocument: '导出', exportAllFrames: '导出所有帧', exportSpriteSheet: '导出精灵表', openTimelapse: '缩时动画', openProjectInfo: '项目信息',
  'tool.airbrush': '喷枪', 'tool.pencil': '画笔', 'tool.eraser': '橡皮擦', 'tool.selection': '矩形选区', 'tool.selection.ellipse': '椭圆选区', 'tool.move': '移动工具', 'tool.shape': '形状工具', 'tool.line': '直线工具', 'tool.curve': '曲线工具', 'tool.fill': '油漆桶', 'tool.fill.gradient': '渐变工具', 'tool.eyedropper': '吸管', 'tool.hand': '抓手', 'tool.zoom': '缩放工具', 'tool.rotate': '旋转视图',
  'tool.shape.rectangleOutline': '矩形轮廓', 'tool.shape.rectangle': '填充矩形', 'tool.shape.ellipseOutline': '椭圆轮廓', 'tool.shape.ellipse': '填充椭圆',
  lasso: '套索选区', polygonLasso: '多边形套索', magic: '魔棒选区', canvasResize: '调整画布大小', imageResize: '调整图像大小', transform: '变换', outline: '描边', adjustmentColorBalance: '色彩平衡', adjustmentBrightnessContrast: '亮度/对比度', adjustmentHueSaturation: '色相/饱和度', adjustmentCurves: '曲线', openShortcutSettings: '快捷键设置', openPreferences: '首选项', flipVertical: '垂直翻转', flipHorizontal: '水平翻转', selectAll: '全选', invertSelection: '反选选区', deselect: '取消选择', createBrushFromSelection: '从选区创建笔刷',
  copy: '复制', cut: '剪切', paste: '粘贴', pasteAsNewLayer: '粘贴为新图层', pasteAsNewDocument: '粘贴为新项目', save: '保存', saveAs: '另存为', undo: '撤销', redo: '重做', relativeLuminance: '查看相对明暗', advancedMode: '高级模式', fillForeground: '填充前景色', addForegroundToPalette: '按住并点击添加颜色', swapForegroundBackground: '交换前景色与背景色', replaceColor: '替换颜色', convertColorMode: '转换颜色模式', newLayer: '新建图层', createLayerGroup: '新建图层组', toggleSelectedLayerVisibility: '显示或隐藏所选图层', toggleSelectedLayerLock: '锁定或解锁所选图层', toggleSelectedGroupCollapsed: '展开或收起所选图层组', duplicateLayer: '复制图层', mergeLayerDown: '向下合并', mergeSelectedLayers: '合并所选图层', mergeLayerGroup: '合并图层组', mergeVisibleLayers: '合并可见图层', ungroupLayers: '解组', deleteLayer: '删除图层或选区', toggleSelectionOutline: '显示或隐藏蚂蚁线', mirrorView: '水平镜像视图', mirrorViewVertical: '垂直镜像视图', toggleGrid: '显示像素网格', toggleCustomGrid: '显示自定义网格', openGridSettings: '网格设置', rotateViewClockwise90: '顺时针旋转视图 90°', rotateViewCounterClockwise90: '逆时针旋转视图 90°', resetView: '复位视图', toggleColorPanel: '显示或隐藏颜色栏目', togglePalettePanel: '显示或隐藏调色板栏目', toggleLayersPanel: '显示或隐藏图层栏目', togglePreviewPanel: '显示或隐藏预览栏目', toggleTilesetPanel: '显示或隐藏瓦片集栏目', toggleBrushLibraryPanel: '显示或隐藏笔刷库栏目', popupColorPanel: '弹窗式颜色栏目', popupPalettePanel: '弹窗式调色板栏目', popupLayersPanel: '弹窗式图层栏目', popupPreviewPanel: '弹窗式预览栏目', popupTilesetPanel: '弹窗式瓦片集栏目', popupBrushLibraryPanel: '弹窗式笔刷库栏目', toggleTimeline: '显示或隐藏时间轴', toolRailLeft: '工具栏放到左侧', toolRailRight: '工具栏放到右侧', toolRailTop: '工具栏放到顶部', toolRailBottom: '工具栏放到底部', saveWorkspaceLayout: '保存为新工作区', openWorkspaceManager: '管理工作区', openComponentLibrary: '组件库', openLatestRelease: '更新日志', openRoadmap: '未来计划', openAbout: '关于 MoonSprite',
  brushSizeDecrease: '减小笔刷尺寸', brushSizeIncrease: '增大笔刷尺寸', temporaryEyedropper: '临时吸色', temporaryMove: '临时移动工具', copySelectionContent: '复制选区内容', copyLayerOnDrag: '拖动复制图层', constrainAxis: '水平或垂直约束', addToSelection: '加选', proportionalSelectionTransform: '选区固定比例缩放', integerSelectionScale: '选区整数倍缩放', snapSelectionRotation: '选区八方向旋转', snapViewRotation: '视图八方向旋转', resetViewRotation: '旋转视图临时复位', temporaryPan: '临时抓手', brushSizeAdjust: '拖动调整笔刷尺寸', brushSizeWheelAdjust: '滚轮调整笔刷尺寸', lineConnectionMode: '直线连接模式', constrainLineDirections: '约束直线方向'
}

const enLabels: Record<ShortcutId, string> = {
  'tool.slice': 'Slice Tool',
  'tool.text': 'Text Tool',
  toggleClippingMask: 'Clipping Mask',
  toggleAnimationPlayback: 'Play or Pause Animation', previousAnimationFrame: 'Previous Frame', nextAnimationFrame: 'Next Frame', addAnimationFrame: 'Add Frame', addLinkedAnimationFrame: 'New Linked Frame', addBlankAnimationFrame: 'New Blank Frame', deleteAnimationFrame: 'Delete Frame', copyAnimationCel: 'Copy Cel',
  openHome: 'Open Home', newDocument: 'New Project', openDocument: 'Open Project', closeDocument: 'Close Project', openProjectFolder: 'Show in Folder', exportDocument: 'Export', exportAllFrames: 'Export All Frames', exportSpriteSheet: 'Export Sprite Sheet', openTimelapse: 'Timelapse', openProjectInfo: 'Project Information',
  'tool.airbrush': 'Airbrush', 'tool.pencil': 'Pencil', 'tool.eraser': 'Eraser', 'tool.selection': 'Rectangular Selection', 'tool.selection.ellipse': 'Elliptical Selection', 'tool.move': 'Move Tool', 'tool.shape': 'Shape Tool', 'tool.line': 'Line Tool', 'tool.curve': 'Curve Tool', 'tool.fill': 'Paint Bucket', 'tool.fill.gradient': 'Gradient Tool', 'tool.eyedropper': 'Eyedropper', 'tool.hand': 'Hand Tool', 'tool.zoom': 'Zoom Tool', 'tool.rotate': 'Rotate View',
  'tool.shape.rectangleOutline': 'Rectangle Outline', 'tool.shape.rectangle': 'Filled Rectangle', 'tool.shape.ellipseOutline': 'Ellipse Outline', 'tool.shape.ellipse': 'Filled Ellipse',
  lasso: 'Lasso Selection', polygonLasso: 'Polygonal Lasso', magic: 'Magic Wand Selection', canvasResize: 'Canvas Size', imageResize: 'Image Size', transform: 'Transform', outline: 'Outline', adjustmentColorBalance: 'Color Balance', adjustmentBrightnessContrast: 'Brightness/Contrast', adjustmentHueSaturation: 'Hue/Saturation', adjustmentCurves: 'Curves', openShortcutSettings: 'Keyboard Shortcuts', openPreferences: 'Preferences', flipVertical: 'Flip Vertically', flipHorizontal: 'Flip Horizontally', selectAll: 'Select All', invertSelection: 'Invert Selection', deselect: 'Deselect', createBrushFromSelection: 'Create Brush from Selection',
  copy: 'Copy', cut: 'Cut', paste: 'Paste', pasteAsNewLayer: 'Paste as New Layer', pasteAsNewDocument: 'Paste as New Project', save: 'Save', saveAs: 'Save As', undo: 'Undo', redo: 'Redo', relativeLuminance: 'Relative Luminance', advancedMode: 'Advanced Mode', fillForeground: 'Fill with Foreground Color', addForegroundToPalette: 'Hold and Click to Add Color', swapForegroundBackground: 'Swap Foreground and Background', replaceColor: 'Replace Color', convertColorMode: 'Convert Color Mode', newLayer: 'New Layer', createLayerGroup: 'New Layer Group', toggleSelectedLayerVisibility: 'Show or Hide Selected Layers', toggleSelectedLayerLock: 'Lock or Unlock Selected Layers', toggleSelectedGroupCollapsed: 'Expand or Collapse Selected Groups', duplicateLayer: 'Duplicate Layer', mergeLayerDown: 'Merge Down', mergeSelectedLayers: 'Merge Selected Layers', mergeLayerGroup: 'Merge Layer Group', mergeVisibleLayers: 'Merge Visible Layers', ungroupLayers: 'Ungroup', deleteLayer: 'Delete Layer or Selection', toggleSelectionOutline: 'Show or Hide Marching Ants', mirrorView: 'Mirror View Horizontally', mirrorViewVertical: 'Mirror View Vertically', toggleGrid: 'Show Pixel Grid', toggleCustomGrid: 'Show Custom Grid', openGridSettings: 'Grid Settings', rotateViewClockwise90: 'Rotate View 90° Clockwise', rotateViewCounterClockwise90: 'Rotate View 90° Counterclockwise', resetView: 'Reset View', toggleColorPanel: 'Show or Hide Color Panel', togglePalettePanel: 'Show or Hide Palette Panel', toggleLayersPanel: 'Show or Hide Layers Panel', togglePreviewPanel: 'Show or Hide Preview Panel', toggleTilesetPanel: 'Show or Hide Tileset Panel', toggleBrushLibraryPanel: 'Show or Hide Brush Library Panel', popupColorPanel: 'Popup Color Panel', popupPalettePanel: 'Popup Palette Panel', popupLayersPanel: 'Popup Layers Panel', popupPreviewPanel: 'Popup Preview Panel', popupTilesetPanel: 'Popup Tileset Panel', popupBrushLibraryPanel: 'Popup Brush Library Panel', toggleTimeline: 'Show or Hide Timeline', toolRailLeft: 'Move Toolbar to Left', toolRailRight: 'Move Toolbar to Right', toolRailTop: 'Move Toolbar to Top', toolRailBottom: 'Move Toolbar to Bottom', saveWorkspaceLayout: 'Save as New Workspace', openWorkspaceManager: 'Manage Workspaces', openComponentLibrary: 'Component Library', openLatestRelease: 'Release Notes', openRoadmap: 'Roadmap', openAbout: 'About MoonSprite',
  brushSizeDecrease: 'Decrease Brush Size', brushSizeIncrease: 'Increase Brush Size', temporaryEyedropper: 'Temporary Eyedropper', temporaryMove: 'Temporary Move Tool', copySelectionContent: 'Copy Selection Content', copyLayerOnDrag: 'Duplicate Layer While Dragging', constrainAxis: 'Constrain Horizontally or Vertically', addToSelection: 'Add to Selection', proportionalSelectionTransform: 'Proportional Selection Scale', integerSelectionScale: 'Integer Selection Scale', snapSelectionRotation: 'Snap Selection Rotation to 8 Directions', snapViewRotation: 'Snap View Rotation to 8 Directions', resetViewRotation: 'Temporarily Reset View Rotation', temporaryPan: 'Temporary Hand Tool', brushSizeAdjust: 'Drag to Adjust Brush Size', brushSizeWheelAdjust: 'Wheel to Adjust Brush Size', lineConnectionMode: 'Line Connection Mode', constrainLineDirections: 'Constrain Line Directions'
}

export const shortcutGroupLabelsByLocale: Record<AppLocale, Record<ShortcutGroupId, string>> = {
  'zh-CN': zhGroups,
  'en-US': enGroups
}

export const shortcutLabelsByLocale: Record<AppLocale, Record<ShortcutId, string>> = {
  'zh-CN': zhLabels,
  'en-US': enLabels
}
